name: PHP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build e Teste PHP
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Faz checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2️⃣ Configura a versão do PHP
      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      # 3️⃣ Instala dependências com Composer
      - name: Instalar dependências
        run: |
          composer install --no-interaction --no-progress --prefer-dist

      # 4️⃣ (Opcional) Valida o composer.json e o autoload
      - name: Validar composer.json e autoload
        run: |
          composer validate --no-check-lock
          composer dump-autoload --optimize

      # 5️⃣ (Opcional) Executa testes
      - name: Executar testes (PHPUnit)
        run: |
          if [ -f vendor/bin/phpunit ]; then
            vendor/bin/phpunit --colors=always
          else
            echo "⚠️ Nenhum teste encontrado."
          fi
